module-name: eventing-auth-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/eventing-auth-manager:v20231024-13884189
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
