name: Integration

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  ias-integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install Kyma CLI & setup k3d cluster using Kyma CLI
      run: |
        make provision-k3d
        bin/k3d kubeconfig get k3d > k3d_kubeconfig

    - name: Test
      run: |
        make test
      env:
        USE_EXISTING_CLUSTER: true 
        KUBECONFIG: k3d_kubeconfig
        TEST_EVENTING_AUTH_TARGET_KUBECONFIG_PATHr: k3d_kubeconfig
        TEST_EVENTING_AUTH_IAS_URL: ${{ secrets.TEST_EVENTING_AUTH_IAS_URL }}
        TEST_EVENTING_AUTH_IAS_USER: ${{ secrets.TEST_EVENTING_AUTH_IAS_USER }}
        TEST_EVENTING_AUTH_IAS_PASSWORD: ${{ secrets.TEST_EVENTING_AUTH_IAS_PASSWORD }}
